version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
      - image: 'circleci/mariadb:latest'
    steps:
      - checkout
      - run: npm install
      - run: npm run db:up
      - run: npm run lint
      - run: npm run build
      - run: npm run test:cov
      - run: bundle exec rspec spec
