import { MigrationInterface, QueryRunner, Table } from 'typeorm';

export class Users1594945067050 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'users',
        columns: [
          {
            name: 'id',
            type: 'int',
            length: '11',
            isPrimary: true,
            isGenerated: true,
            generationStrategy: 'increment',
            comment: 'The internal id for the user account.',
          },
          {
            name: 'account_id',
            type: 'varchar',
            length: '36',
            isGenerated: true,
            generationStrategy: 'uuid',
            comment: 'The external (public) account id for the user account.',
          },
          {
            name: 'email',
            type: 'VARCHAR',
            length: '255',
            comment: 'The email address used for the user account.',
          },
          {
            name: 'password_hash',
            type: 'BINARY',
            length: '60',
            comment:
              'The password hash generated by bcrypt for the user account.',
          },
          {
            name: 'updated_at',
            type: 'datetime',
            length: '6',
            default: 'current_timestamp(6)',
            comment: 'The date the user account record was last updated.',
          },
          {
            name: 'deleted_at',
            type: 'datetime',
            length: '6',
            isNullable: true,
            default: null,
            comment: 'The date the user account was deleted.',
          },
        ],
        indices: [
          {
            name: 'email_ix',
            columnNames: ['email'],
            isUnique: true,
          },
        ],
      }),
      true,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('users');
  }
}
